#+title: Session 1---Pokémon Types
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="css/main_theme.css" />

* Introduction

Due to time constraints, I believe it to be more instructive to take
a "learning by osmosis" approach to programming, and work a practical
example during the seminar.
The first session will introduce the most basic concepts in python as well as
the ~csv~ package, which is used to deal with csv files.

* Getting Help

Since by definition this style of teaching will omit many of the fundamentals,
it will be up to you to learn them yourself.
Hopefully by the end of this session you will have seen enough to be able
to read the [[https://docs.python.org/3/tutorial/index.html][Python Tutorial]] on your own.
The first 6 chapters should suffice for an introduction.
The [[https://docs.python.org/3/library/csv.html][CSV package reference]] is quite short and can be read in 20-30 minutes.
For general help there is also the
[[https://docs.python.org/3/library/index.html][library reference]] (may be hard to read) or the slightly easier but less
comprehensive [[https://www.w3schools.com/python/python_reference.asp][reference on w3schools]].



* The Problem Statement

Today, we are playing pokemon. Specifically we are playing a modified version
of pokemon called [[https://www.pokecommunity.com/threads/pokemon-too-many-types-as-seen-in-alpharads-video.501317/][Too Many Types]].
Each pokemon has up to three types and each move has one type.
When a pokemon attacks another with a move, the move's type is compared
against all the defending pokemon's types.
In each case the move can be
neutral (deals normal damage),
super effective (deals double damage),
not very effective (deals half damage),
or have no effect at all.
To determine how effective an attack is against a defender,
multiply the above modifiers for each of the defender's types.

Doing this by hand is too tedious as there are too many types in this version.
Therefore, we will write a program to do it for us.
Fortunately all information we need is available in a [[https://docs.google.com/spreadsheets/d/1WxYmHs_ZsgzLUrL8WfEGN-JHdToubXHvi942ViDIG8k/][spreadsheet]] online.
I have exported the relevant parts to csv files and cleaned them up slightly.
You can download [[file:resources/pokedex.csv][pokedex.csv]] and [[file:resources/typechart.csv][typechart.csv]] if you wish to follow along.
